document.addEventListener('DOMContentLoaded',()=>{const f=document.getElementById('form'),pl=document.querySelector('.planner'),st=[...document.querySelectorAll('.planner > aside .step')];if(!f||!pl||st.length!==4)return;const n=['Datos generales','Contenido y PDA','Contexto','Generar'],t=['🏫 Datos generales','📚 Contenido y PDA','📝 Contexto y necesidades del grupo','✨ Revisión y generación'];const p=n.map((_,i)=>{const x=document.createElement('section');x.className='wizard-panel';x.innerHTML=`<div class="panel-kicker">PASO ${i+1} DE 4</div><h2 class="panel-title">${t[i]}</h2>`;return x});st.forEach((s,i)=>{s.innerHTML=`<strong>${i+1}</strong><span>${n[i]}</span>`});const plan=document.getElementById('planning-data'),ch=[...f.querySelectorAll(':scope > h2')].find(x=>/datos curriculares/i.test(x.textContent)),gh=[...f.querySelectorAll(':scope > h2')].find(x=>/contenido y pda/i.test(x.textContent));const move=id=>document.getElementById(id)?.closest('label');if(plan){p[0].append(plan.querySelector('h2'),plan.querySelector('.section-help'));['schoolName','schoolCct','schoolLocality','schoolZone','startDate'].forEach(id=>{let x=move(id);if(x)p[0].appendChild(x)})}if(ch){p[1].appendChild(ch);let g=ch.nextElementSibling;if(g&&g.classList.contains('grid'))p[1].appendChild(g)}if(plan){['scenario','methodology','projectName'].forEach(id=>{let x=move(id);if(x)p[1].appendChild(x)});let a=plan.querySelector('.axes-box');if(a)p[1].appendChild(a)}if(gh)p[1].appendChild(gh);['content','pda'].forEach(id=>{let x=move(id);if(x)p[1].appendChild(x)});let c=move('context');if(c)p[2].appendChild(c);let ai=f.querySelector('.ai-note'),ac=f.querySelector('.actions');if(ai)p[3].appendChild(ai);if(ac)p[3].appendChild(ac);const w=document.createElement('div');w.className='wizard-panels';p.forEach(x=>w.appendChild(x));f.appendChild(w);[...f.children].forEach(x=>{if(x!==w)x.style.display='none'});let cur=1;function show(i){cur=Math.max(1,Math.min(4,i));p.forEach((x,j)=>x.classList.toggle('active',j===cur-1));st.forEach((x,j)=>{x.classList.toggle('active',j===cur-1);x.classList.toggle('done',j<cur-1)});if(cur===2){
  let box=document.getElementById('pda-options');
  if(box)p[1].appendChild(box);
}

if(cur===4){
  if(typeof window.updatePlanningReview==='function'){
    window.updatePlanningReview();
  }
}}st.forEach((s,i)=>s.onclick=()=>show(i+1));p.forEach((x,i)=>{let nav=document.createElement('div');nav.className='wizard-navigation';if(i){let b=document.createElement('button');b.type='button';b.className='wizard-prev';b.textContent='← Anterior';b.onclick=()=>show(i);nav.appendChild(b)}if(i<3){let b=document.createElement('button');b.type='button';b.className='wizard-next';b.textContent='Continuar →';b.onclick=()=>show(i+2);nav.appendChild(b)}x.appendChild(nav)});show(1)});const s=document.createElement('style');s.textContent='.planner{display:grid!important;grid-template-columns:245px minmax(0,1fr)!important;gap:22px!important}.wizard-panel{display:none!important;background:#fff;border:1px solid #e9e4f2;border-radius:20px;padding:25px;min-height:430px}.wizard-panel.active{display:block!important}.wizard-panels{min-width:0}.planner>aside .step{cursor:pointer!important}.wizard-navigation{display:flex;justify-content:space-between;margin-top:24px;padding-top:18px;border-top:1px solid #eee}.wizard-navigation button{border:0;border-radius:11px;padding:11px 18px;font-weight:700;cursor:pointer}.wizard-next{background:#713bd0;color:#fff}.wizard-prev{background:#f3f1f7;color:#625b6d}@media(max-width:800px){.planner{grid-template-columns:1fr!important}}';document.head.appendChild(s);